FlightTicket/FlightTicket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from booksystem import views

urlpatterns = [
    url(r'^booksystem/admin/', admin.site.urls),
    url(r'^booksystem/admin/finance', views.admin_finance, name='admin_finance'),  # 财务管理
    url(r'^booksystem/', include('booksystem.urls')),
	url(r'', include('booksystem.urls')),
]

FlightTicket/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from booksystem import views

urlpatterns = [
    url(r'^booksystem/admin/', admin.site.urls),
    url(r'^booksystem/admin/finance', views.admin_finance, name='admin_finance'),  # 财务管理
    url(r'^booksystem/', include('booksystem.urls')),
	url(r'', include('booksystem.urls')),
]

booksystem/urls.py
from django.conf.urls import url
from . import views

app_name = 'booksystem'  # 添加这个属性，方便jinja语法

urlpatterns = [
    # 注册与登录
    url(r'^register/$', views.register, name='register'),  # 注册
    url(r'^login_user/$', views.login_user, name='login_user'),  # 登入
    url(r'^logout_user/$', views.logout_user, name='logout_user'),  # 登出

    # 主要页面
    url(r'^$', views.index, name='index'),  # 欢迎页面
    url(r'^result/$', views.result, name='result'),  # 搜索结果
    url(r'^user_operation/$', views.user_operation, name='user_operation'),  # 用户信息
    url(r'^user_bill/$', views.user_bill, name='user_bill'),  # 用户账单
    url(r'^book/flight/(?P<flight_id>[0-9]+)/$', views.book_ticket, name='book_ticket'),  # 订票
    url(r'^refund/flight/(?P<flight_id>[0-9]+)/$', views.refund_ticket, name='refund_ticket'),  # 退票
    url(r'^fetch/flight/(?P<flight_id>[0-9]+)/$', views.fetch_ticket, name='fetch_ticket'),  # 取票
    url(r'^pay/flight/(?P<flight_id>[0-9]+)/$', views.pay_ticket, name='pay_ticket'),  # 付款
]

booksystem/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


# Create your models here.
# 添加primary_key会覆盖掉默认的主键
class Flight(models.Model):
	user = models.ManyToManyField(User, default=1)  # 有了这个字段之后，默认的后台添加失效，必须要自定义Form，除去这个字段
	name = models.CharField(max_length=100)  # 班次  南方航空CZ3969
	leave_city = models.CharField(max_length=100, null=True)  # 离开城市
	arrive_city = models.CharField(max_length=100, null=True)  # 到达城市
	leave_airport = models.CharField(max_length=100, null=True)  # 离开的车场
	arrive_airport = models.CharField(max_length=100, null=True)  # 到达的车场
	leave_time = models.DateTimeField(null=True)  # DateTimeField包括了DateField信息，并且添加了时间
	arrive_time = models.DateTimeField(null=True)
	capacity = models.IntegerField(default=0, null=True)  # 经济舱座位总数
	price = models.FloatField(default=0, null=True)  # 价格
	book_sum = models.IntegerField(default=0, null=True)  # 订票总人数
	income = models.FloatField(default=0, null=True)  # 收入
	SEAT_TYPE = (
		('头等舱','头等舱'),
		('公务舱','公务舱'),
		('经济舱','经济舱')
		)
	seat_type = models.CharField(max_length=100,choices=SEAT_TYPE, default='经济舱')
	# bill = models.FloatField(default=0, null=True) #账单
	# seat_type = models.CharField(max_length, null=True)
	def __str__(self):
		return self.name

class Order(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE,)
	flight = models.ForeignKey(Flight, on_delete=models.CASCADE,)
	creat_time = models.DateTimeField(null=True, auto_now_add=True)
	pay_time = models.DateTimeField(null=True)
	fetch_time = models.DateTimeField(null=True)
	refund_time = models.DateTimeField(null=True)
	# is_pay = models.BooleanField(default=False)
	is_pay = models.BooleanField(default=False)
	is_fetch = models.BooleanField(default=False)
	is_refund = models.BooleanField(default=False)
	can_modify = models.BooleanField(default=True)
	def __str__(self):
		return self.user.username+self.flight.name

# class Bill(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE,)
#     flight = models.ForeignKey(Flight, on_delete=models.CASCADE,)
#     order = models.ForeignKey(Order, on_delete=models.CASCADE,)    

booksystem/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Flight,Order


class PassengerInfoForm(forms.Form):
    leave_city = forms.CharField(label='leave_city', max_length=100)
    arrive_city = forms.CharField(label='arrive_city', max_length=100)
    leave_date = forms.DateField(label='leave_date')


# 自定义Flight对象的输入信息
class FlightForm(forms.ModelForm):
    class Meta:
        model = Flight
        exclude = ['user']  # user信息不能从后台输入

# 自定义Order对象的输入信息
class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        exclude = []  # user信息不能从后台输入

# 用户需要输入的字段
class UserForm(forms.ModelForm):
    # username = forms.CharField(
    #     min_length=6,
    #     label="username",
    #     error_messages={
    #         "required": "不能为空",
    #         "invalid": "格式错误",
    #         "min_length": "用户名最短6位"
    #     }
    # )
    password = forms.CharField(
        widget=forms.PasswordInput,
        min_length=6,
        label="password",
        error_messages={
            "required": "不能为空",
            "invalid": "格式错误",
            "min_length": "密码最短6位"
        }
    )
    # ID = forms.CharField(
    #     )
    class Meta:
        model = User
        fields = ['username', 'email', 'password']

# class UserForm(forms.Form):
#     username = forms.CharField(
#         min_length=8,
#         label="用户名",
#         initial="张三",
#         error_messages={
#             "required": "不能为空",
#             "invalid": "格式错误",
#             "min_length": "用户名最短8位"
#         }
#     )
#     pwd = forms.CharField(min_length=6, label="密码")

booksystem/views.py
# -*- coding: utf-8 -*-
# @Author: XXG
# @Date:   2024-06-07 09:14:20
# @Last Modified by:   XXG
# @Last Modified time: 2024-06-07 10:52:40
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from .forms import PassengerInfoForm, UserForm
from .models import Flight, Order
from .classes import IncomeMetric
from .classes import Order as ClassOrder
from django.contrib.auth.models import Permission, User
import datetime, pytz
from operator import attrgetter
from django.utils import timezone

ADMIN_ID = 1


# 管理员后台财务管理
# 统计航空公司每周、每月，每年营业收入情况。
def admin_finance(request):
    all_Trains = Flight.objects.all()
    all_Trains = sorted(all_Trains, key=attrgetter('leave_time'))  # 将所有车次按照出发时间排序

    # 将车次每天的输入打上不同的时间标签 [周，月，日]
    week_day_incomes = []
    month_day_incomes = []
    year_day_incomes = []

    # 用set存储所有的 周，月，年
    week_set = set()
    month_set = set()
    year_set = set()
    for flight in all_Trains:
        if flight.income > 0:  # 只统计有收入的车次
            # 打上周标签
            this_week = flight.leave_time.strftime('%W')  # datetime获取周
            week_day_incomes.append((this_week, flight.income))  # 添加元组(week, income)
            week_set.add(this_week)
            # 打上月标签
            this_month = flight.leave_time.strftime('%m')  # datetime获取月
            month_day_incomes.append((this_month, flight.income))  # 添加元组(month, income)
            month_set.add(this_month)
            # 打上年标签
            this_year = flight.leave_time.strftime('%Y')  # datetime获取年
            year_day_incomes.append((this_year, flight.income))  # 添加元组(year, income)
            year_set.add(this_year)

    # 存储每周收入
    # 将每周的收入用 IncomeMetric 类型存储在 week_incomes List中
    week_incomes = []
    for week in week_set:
        income = sum(x[1] for x in week_day_incomes if x[0] == week)  # 同周次的income求和
        flight_sum = sum(1 for x in week_day_incomes if x[0] == week)  # 同周次的车次总数目
        week_income = IncomeMetric(week, flight_sum, income)  # 将数据存储到IncomeMetric类中，方便jinja语法
        week_incomes.append(week_income)
    week_incomes = sorted(week_incomes, key=attrgetter('metric'))  # 将List类型的 week_incomes 按周次升序排列

    # 存储每月收入
    # 将每月的收入用 IncomeMetric 类型存储在 month_incomes List中
    month_incomes = []
    for month in month_set:
        income = sum(x[1] for x in month_day_incomes if x[0] == month)
        flight_sum = sum(1 for x in month_day_incomes if x[0] == month)
        month_income = IncomeMetric(month, flight_sum, income)
        month_incomes.append(month_income)
    month_incomes = sorted(month_incomes, key=attrgetter('metric'))  # 将List类型的 month_incomes 按月份升序排列

    # 存储每年收入
    # 将每年的收入用 IncomeMetric 类型存储在 year_incomes List中
    year_incomes = []
    for year in year_set:
        income = sum(x[1] for x in year_day_incomes if x[0] == year)
        flight_sum = sum(1 for x in year_day_incomes if x[0] == year)
        year_income = IncomeMetric(year, flight_sum, income)
        year_incomes.append(year_income)
    year_incomes = sorted(year_incomes, key=attrgetter('metric'))  # 将List类型的 year_incomes 按年份升序排列

    # 存储order信息
    passengers = User.objects.exclude()  # 去掉管理员
    order_set = set()
    for p in passengers:
        # Trains = Flight.objects.filter(user=p)
        # for f in Trains:
        #     route = f.leave_city + ' → ' + f.arrive_city
        #     order = ClassOrder(p.username, f.name, route, f.leave_time, f.price)
        #     order_set.add(order)
        orders = Order.objects.filter(user=p)
        for o in orders:
            route = o.flight.leave_city + ' → ' + o.flight.arrive_city
            if o.is_pay:
                pay_information = '已支付'
            else :
                pay_information = '未支付'
            if o.is_fetch:
                fetch_information = '已取票'
            else :
                fetch_information = '未取票'
            if o.is_refund:
                refund_information = '已退票'
            else :
                refund_information = '未退票'
            order = ClassOrder(p.username, o.creat_time, o.flight.name, route, 
                o.flight.leave_time, o.flight.price,
                pay_information, fetch_information, refund_information)
            order_set.add(order)

    # 信息传给前端
    context = {
        'week_incomes': week_incomes,
        'month_incomes': month_incomes,
        'year_incomes': year_incomes,
        'order_set': order_set
    }
    return context


# 显示用户订单信息
# 车次信息，退票管理
def user_operation(request):
    if request.user.is_authenticated:
        # 如果用户是管理员，render公司车次收入统计信息页面 admin_finance
        # if request.user.id == ADMIN_ID:
        #     #context = admin_finance(request)  # 获取要传入前端的数据
        #     context = admin_finance(request)
        #     return render(request, 'booksystem/admin_finance.html', context)
        # 如果用户是普通用户，render用户的车票信息 user_info
        # else:
            booked_Trains = Flight.objects.filter(user=request.user)  # 从 booksystem_flight_user 表过滤出该用户订的车次
            context = {
                'booked_Trains': booked_Trains,
                'username': request.user.username,  # 导航栏信息更新
            }
            return render(request, 'booksystem/user_operation.html', context)
    return render(request, 'booksystem/login.html')  # 用户如果没登录，render登录页面

#个人账单
def user_bill(request):
    if request.user.is_authenticated:
        # 如果用户是管理员，render公司车次收入统计信息页面 admin_finance
        if request.user.id == ADMIN_ID:
            #context = admin_finance(request)  # 获取要传入前端的数据
            context = admin_finance(request)
            return render(request, 'booksystem/admin_finance.html', context)
        # 如果用户是普通用户，render用户的车票信息 user_info
        else:
            order_set = set()
            # Trains = Flight.objects.filter(user=request.user)
            orders = Order.objects.filter(user=request.user)
            for o in orders:
                route = o.flight.leave_city + ' → ' + o.flight.arrive_city
                if o.is_pay:
                    pay_information = '已支付'
                else :
                    pay_information = '未支付'
                if o.is_fetch:
                    fetch_information = '已取票'
                else :
                    fetch_information = '未取票'
                if o.is_refund:
                    refund_information = '已退票'
                else :
                    refund_information = '未退票'
                order = ClassOrder(request.user.username, o.creat_time, o.flight.name, route, 
                    o.flight.leave_time, o.flight.price,
                    pay_information, fetch_information, refund_information)
                order_set.add(order)
            # booked_Trains = Flight.objects.filter(user=request.user)  # 从 booksystem_flight_user 表过滤出该用户订的车次
            context = {
                'order_set': order_set,
                'username': request.user.username,  # 导航栏信息更新
            }
            return render(request, 'booksystem/user_bill.html', context)
    return render(request, 'booksystem/login.html')  # 用户如果没登录，render登录页面

# 主页
# 欢迎页面性质的订票页面
def index(request):
    return render(request, 'booksystem/index.html')


# 免除csrf
@csrf_exempt
def book_ticket(request, flight_id):
    if not request.user.is_authenticated:  # 如果没登录就render登录页面
        return render(request, 'booksystem/login.html')
    else:
        flight = Flight.objects.get(pk=flight_id)
        # 查看乘客已经订购的Trains
        booked_Trains = Flight.objects.filter(user=request.user)  # 返回 QuerySet

        if flight in booked_Trains:
            return render(request, 'booksystem/book_conflict.html')

        # book_flight.html 点确认之后，request为 POST 方法，虽然没有传递什么值，但是传递了 POST 信号
        # 确认订票，flight数据库改变

        # 验证一下，同样的车票只能订一次
        if request.method == 'POST':
            if flight.capacity > flight.book_sum:
                flight.book_sum += 1
                # flight.capacity -= 1
                flight.income += flight.price
                flight.user.add(request.user)
                flight.save()  # 一定要记着save
                order = Order()
                order.user = request.user
                order.flight = flight
                order.save()
        # 传递更改之后的票务信息
        context = {
            'flight': flight,
            'username': request.user.username,
            'surplus' : flight.capacity - flight.book_sum
        }
        return render(request, 'booksystem/book_flight.html', context)


# 退票
def refund_ticket(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    order = Order.objects.filter(user = request.user)
    for o in order:
        if o.can_modify == True and o.flight == flight and o.is_refund != True and o.is_fetch != True:
            flight.book_sum -= 1
            # flight.capacity += 1
            flight.income -= flight.price
            flight.user.remove(request.user)
            flight.save()
            o.is_refund = True
            o.can_modify = False
            o.refund_time = timezone.now()
            o.save()
            return HttpResponseRedirect('/booksystem/user_operation')
    # order = Order.objects.get(user = request.user, flight = flight)
    # order.is_refund
    return render(request, 'booksystem/refund_failure.html')

def fetch_ticket(request, flight_id):
    flight = Flight.objects.get(pk=flight_id)
    surplus = (flight.leave_time - timezone.now()).days
    order = Order.objects.filter(user = request.user)
    for o in order:
        if o.can_modify == True and o.flight == flight and o.is_refund != True and o.is_fetch != True and o.is_pay == True:
            if surplus <= 1:
                o.is_fetch = True
                o.can_modify = False
                o.fetch_time = timezone.now()
                o.save()
                return render(request, 'booksystem/fetch_success.html')
            else:
                return render(request, 'booksystem/fetch_time_failure.html')

booksystem/templates/booksystem/admin_finance.html
{% extends 'booksystem/base.html' %}
{% block login_display %}
    <a href="#">欢迎您 admin </a> <!--用#就不会跳转了-->
{% endblock %}


{% block content %}

    <div class="container-fluid col-sm-12" style="margin-top: 20px">
        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel panel-heading">
                    周收入
                </div>
                <div>
                    <table class="table table-bordered table-striped">
                        <thead>
                        <th style="text-align: center">编号</th>
                        <th style="text-align: center">周次</th>
                        <th style="text-align: center">车次架次</th>
                        <th style="text-align: center">收入</th>
                        </thead>
                        <tbody align="center">
                        {% for income in week_incomes %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ income.metric }}</td>
                                <td>{{ income.flight_sum }}</td>
                                <td>{{ income.income }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel panel-heading">
                    月收入
                </div>
                <div>
                    <table class="table table-bordered table-striped">
                        <thead>
                        <th style="text-align: center">编号</th>
                        <th style="text-align: center">月份</th>
                        <th style="text-align: center">车次架次</th>
                        <th style="text-align: center">收入</th>
                        </thead>
                        <tbody align="center">
                        {% for income in month_incomes %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ income.metric }}</td>
                                <td>{{ income.flight_sum }}</td>
                                <td>{{ income.income }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="panel panel-primary">
                <div class="panel panel-heading">
                    年收入
                </div>
                <div>
                    <table class="table table-bordered table-striped">
                        <thead>
                        <th style="text-align: center">编号</th>
                        <th style="text-align: center">年份</th>
                        <th style="text-align: center">车次架次</th>
                        <th style="text-align: center">收入</th>
                        </thead>
                        <tbody align="center">
                        {% for income in year_incomes %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ income.metric }}</td>
                                <td>{{ income.flight_sum }}</td>
                                <td>{{ income.income }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>


        <div class="book_orders" style="margin-left: 20px;margin-right: 20px">
            <div class="col-sm-12" style="background-color: white">
                <h1>订单列表</h1>
                <div>
                    <table class="table table-bordered table-striped">
                        <thead>
                        <th style="text-align: center">编号</th>
                        <th style="text-align: center">创建时间</th>
                        <th style="text-align: center">旅客</th>
                        <th style="text-align: center">车次</th>
                        <th style="text-align: center">路线</th>
                        <th style="text-align: center">出发时间</th>
                        <th style="text-align: center">票价</th>
                        <th style="text-align: center">支付信息</th>
                        <th style="text-align: center">取票信息</th>
                        <th style="text-align: center">退票信息</th>
                        </thead>
                        <tbody align="center">
                        {% for order in order_set %}
                            <tr>
                                <td>{{ forloop.counter }}</td>
                                <td>{{ order.create_time }}</td>
                                <td>{{ order.passenger_name }}</td>
                                <td>{{ order.flight_name }}</td>
                                <td>{{ order.flight_route }}</td>
                                <td>{{ order.flight_ltime }}</td>
                                <td>￥{{ order.flight_price }}</td>
                                <td>{{ order.is_pay }}</td>
                                <td>{{ order.is_fetch }}</td>
                                <td>{{ order.is_refund }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

booksystem/templates/booksystem/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>车票管理系统</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {#    <link rel="stylesheet" href="../../static/css/bootstrap.min.css">#}
    {% block style %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</head>
<body style="background-color: #f1f1f1">
<nav class="nav navbar-inverse">
    <div class="container-fluid">
        <!-- Header -->
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'booksystem:index' %}">鞋城旅行: 高铁订票</a>
        </div>
        <!-- Items -->
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="{% url 'booksystem:result' %}">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>&nbsp; 购票
                </a>
            </li>
            <li>
                <a href="{% url 'booksystem:user_bill' %}">
                    <span class="glyphicon glyphicon-print" aria-hidden="true"></span>&nbsp; 账单
                </a>
            </li>
            <li>
                <a href="{% url 'booksystem:user_operation' %}">
                    <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; 个人中心
                </a>
            </li>
                        <li>
                {% block login_display %} <!--在用户登录之后改变这一块的显示内容-->
                    <a href="{% url 'booksystem:login_user' %}">
                        <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>&nbsp; 登录
                    </a>
                {% endblock %}
            </li>
            <li>
                <a href="{% url 'booksystem:logout_user' %}">
                    <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; 退出
                </a>
            </li>
        </ul>
    </div>
</nav>

{% block content %}
{% endblock %}

</body>
</html>

booksystem/templates/booksystem/book_conflict.html
{% extends 'booksystem/base.html' %}

{% block login_display %}
    <a href="#">欢迎您 {{ username }} </a> <!--用#就不会跳转了-->
{% endblock %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="alert" style="background-color: white;overflow: hidden"> <!--超出部分也是白色底-->
            <h1>尊敬的旅客</h1>
            <div id="info_body" style="margin-left: 50px;margin-right: 50px">
                <p>
                    您已经订购过该车次，请选择其他车次，祝您旅途愉快！
                </p>
            </div>

            <div id="book_btns" align="right">
                <!--div内容右对齐-->
                <a href="javascript:" class="btn btn-danger" style="width: 80px" onclick="javascript:history.back();">返回</a>
            </div>
        </div>
    </div>
{% endblock %}

booksystem/templates/booksystem/fetch_no_pay.html
{% extends 'booksystem/base.html' %}

{% block login_display %}
    <a href="#">欢迎您 {{ username }} </a> <!--用#就不会跳转了-->
{% endblock %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="alert" style="background-color: white;overflow: hidden"> <!--超出部分也是白色底-->
            <h1>尊敬的旅客</h1>
            <div id="info_body" style="margin-left: 50px;margin-right: 50px">
                <p>
                    抱歉，您的订单尚未支付，无法取票，请支付完成后再取票，祝您旅途愉快！
                </p>
            </div>

            <div id="book_btns" align="right">
                <!--div内容右对齐-->
                <a href="javascript:" class="btn btn-danger" style="width: 80px" onclick="javascript:history.back();">返回</a>
            </div>
        </div>
    </div>
{% endblock %}

booksystem/templates/booksystem/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>数据库大作业: 高铁订票</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    {% load static %}
    <style>
        body {
            /*background: url("../../static/img/train-bg.png");*/
            background: url("{% static 'img/train-bg.png' %}");
            background-size: cover; /*自适应浏览器*/
        }
    </style>

</head>
<body>

<!--导航条适应背景色-->
{#<nav class="navbar nav-divider">#}
{#    <div class="container-fluid" style="margin-top: 10px">#}
{#        <div class="navbar-header">#}
{#            <a class="navbar-brand" href="" style="color: ghostwhite; font-size: 50px;">CSU Airlines</a>#}
{#        </div>#}
{#        <div class="navbar-right">#}
{#            <a class="navbar-brand" href="" style="color: ghostwhite; font-size: 24px;">LOG IN</a>#}
{#        </div>#}
{##}
{#    </div>#}
{#</nav>#}

<div class="container-fluid" style="position:absolute; top:50%; left:50%; transform:translate(-50%, -50%); width: 400px; background: rgba(255,255,255,0.9); padding: 30px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0,0,0,0.1);">
    <h3 style="color: black; text-align: center; margin-bottom: 30px;">鞋城旅行: 高铁 查询-购票 一站式服务系统</h3>
    <form class="form-horizontal" role="form" action="{% url 'booksystem:result' %}" method="post">
        {% csrf_token %}
        <div class="input-group">
            <label for="leave_city" class="input-group-addon">出发地</label>
            <input id="leave_city" type="text" name="leave_city" class="form-control" placeholder="城市名称">
        </div>
        <br>
        <div class="input-group">
            <label for="arrive_city" class="input-group-addon">目标地</label>
            <input id="arrive_city" type="text" name="arrive_city" class="form-control" placeholder="城市名称">
        </div>
        <br>
        <div class="input-group">
            <label for="leave_date" class="input-group-addon">出发日期</label>
            <input id="leave_date" type="date" name="leave_date" class="form-control" placeholder="Date">
        </div>
        <br>
        <center>
            <button type="submit" class="btn btn-success">数据库大作业, 启动!</button>
        </center>
    </form>
</div>

</body>
</html>

booksystem/templates/booksystem/login.html
{% extends 'booksystem/base.html' %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">
        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <center>
                            <h1>登录账号</h1><br>
                        </center>
                        <form class="form-horizontal" role="form" action="{% url 'booksystem:login_user' %}" method="post"
                              enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="form-group">
                                <label class="control-label col-sm-6" for="id_username">
                                    Username:
                                </label>
                                <div class="col-sm-6">
                                    <input id="id_username" maxlength="10" name="username" type="text">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="control-label col-sm-6" for="id_password">
                                    Password:
                                </label>
                                <div class="col-sm-6">
                                    <input id="id_password" maxlength="10" name="password" type="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <div align="center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer" align="center">
                        Don't have an account? <a href="{% url 'booksystem:register' %}">Click here</a> to register.
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

booksystem/templates/booksystem/register.html
{% extends 'booksystem/base.html' %}

{% block content %}
    <div class="container-fluid" style="margin-top: 20px">

        <div class="row">
            <div class="col-sm-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <center>
                            <h1>注册账号</h1><br>
                        </center>
                        <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'booksystem/form_template.html' %}
                            <div class="form-group">
                                <div align="center">
                                    <button type="submit" class="btn btn-success">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                    <div class="panel-footer" align="center">
                        Already have an account? <a href="{% url 'booksystem:login_user' %}">Click here</a> to log in.
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}